import "whatwg-fetch"
import "intl"
import "url-polyfill"
import "core-js/web/dom-collections"
import "core-js/es6/map"
import "core-js/es6/string"
import "core-js/es6/array"
import "core-js/es6/object"
